import Head from "next/head";
import Image from "next/image";
import HomeContainer from "../components/home/HomeContainer";
import styles from "../styles/Home.module.css";
import getCommerce from "../lib/commerce";

const Home = ({ products }) => {
  console.log(products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContainer products={products} />
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const commerce = getCommerce();

  const { data: products } = await commerce.products.list();

  return {
    props: {
      products,
    },
  };
}
